
"""
app/services/ticket_service.py
 
Responsibility:
    - Orchestrates the ticket workflow (create, retrieve, update, list).
    - Owns ticket lifecycle: ID generation, status assignment, storage.
    - Acts as the single source of business logic for ticket operations.
 
Should NOT:
    - Define API endpoints
    - Write prompts or call OpenAI directly
    - Create database connections
    - Contain SQL queries
"""
 
import uuid
 
from app.schemas.ticket import (
    CreateTicketRequest,
    TicketResponse,
    TicketStatus,
    UpdateTicketRequest,
)
 
 
class TicketService:
    """
    Manages the lifecycle of customer support tickets.
 
    State:
        _tickets: Dict[str, TicketResponse]
            In-memory store mapping ticket_id -> TicketResponse.
            Using a dictionary for O(1) lookups by ticket ID.
            NOTE: This is intentional technical debt for Milestone 1.
                  Will be replaced with PostgreSQL in a future milestone.
    """
 
    def __init__(self) -> None:
        # Dictionary-backed in-memory store.
        # Key: ticket_id (str), Value: TicketResponse (schema model, not raw dict).
        # This ensures type safety and consistency throughout the service layer.
        self._tickets: dict[str, TicketResponse] = {}
 
    def create_ticket(self, request: CreateTicketRequest) -> TicketResponse:
        """
        Create a new support ticket and store it.
 
        Business rules applied here (not in the API or agent):
            - Ticket ID is generated by the service (UUID4 for uniqueness).
            - Initial status is always OPEN — the service decides this, not the caller.
            - agent_response starts as None; the agent will populate it later.
 
        Args:
            request: Validated CreateTicketRequest schema from the API layer.
 
        Returns:
            TicketResponse: The created ticket, typed and validated.
        """
 
        # Service owns ID generation.
        # UUID4 is used here as a stateless, collision-resistant approach.
        # When we move to PostgreSQL, the DB will own ID generation instead.
        ticket_id = f"TICKET-{uuid.uuid4().hex[:8].upper()}"
 
        # Business rule: all new tickets start as OPEN.
        # This rule belongs here, not in the route or the agent.
        ticket = TicketResponse(
            ticket_id=ticket_id,
            customer_id=request.customer_id,
            issue=request.issue,
            status=TicketStatus.OPEN,
            agent_response=None,
        )
 
        # Store against ticket_id key for O(1) future lookups.
        self._tickets[ticket_id] = ticket
 
        return ticket
 
    def get_ticket(self, ticket_id: str) -> TicketResponse | None:
        """
        Retrieve a single ticket by its ID.
 
        Returns None (not an exception) when the ticket is not found.
        The API layer is responsible for translating None into a 404 response.
        This keeps HTTP concerns out of the service layer.
 
        Args:
            ticket_id: The unique identifier for the ticket.
 
        Returns:
            TicketResponse if found, None otherwise.
        """
 
        # dict.get() returns None cleanly without raising KeyError.
        return self._tickets.get(ticket_id)
 
    def list_tickets(self) -> list[TicketResponse]:
        """
        Return all tickets currently in the store.
 
        Returns an empty list if no tickets exist (never None).
        Callers should not need to guard against None from a list operation.
 
        Returns:
            List of all TicketResponse objects.
        """
 
        return list(self._tickets.values())
 
    def update_ticket(
        self,
        ticket_id: str,
        request: UpdateTicketRequest,
    ) -> TicketResponse | None:
        """
        Update a ticket's status and/or agent_response.
 
        Business rules applied here:
            - The service validates the ticket exists before updating.
            - Only the fields provided in the request are changed (partial update).
            - Returns None if the ticket is not found.
              The API layer is responsible for translating None into a 404.
            - The caller cannot change ticket_id or customer_id —
              those are immutable once set by create_ticket().
 
        Why partial updates (not full replacement)?
            The agent may update only agent_response.
            A supervisor may update only status.
            Requiring the full object each time would force callers
            to first fetch, then reconstruct, then send — unnecessary coupling.
 
        Args:
            ticket_id: The ticket to update.
            request:   UpdateTicketRequest carrying optional status and/or
                       agent_response fields.
 
        Returns:
            Updated TicketResponse if found, None otherwise.
        """
 
        existing = self._tickets.get(ticket_id)
 
        if existing is None:
            # Return None; do not raise here.
            # HTTP 404 is an API-layer concern, not a service-layer concern.
            return None
 
        # Apply only the fields that were explicitly provided.
        # None means "caller did not supply this field" — leave it unchanged.
        updated_status = (
            request.status if request.status is not None else existing.status
        )
        updated_agent_response = (
            request.agent_response
            if request.agent_response is not None
            else existing.agent_response
        )
 
        # Business rule: reconstruct as a new TicketResponse rather than
        # mutating the existing object in place.
        # This keeps objects predictable and avoids hidden side effects,
        # which matters when we later add evaluation or audit logging.
        updated_ticket = TicketResponse(
            ticket_id=existing.ticket_id,
            customer_id=existing.customer_id,
            issue=existing.issue,
            status=updated_status,
            agent_response=updated_agent_response,
        )
 
        self._tickets[ticket_id] = updated_ticket
 
        return updated_ticket
    