
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api

    env_file:
      - ../.env.docker

    ports:
      - "8000:8000"

    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine

    environment:
      POSTGRES_DB: customer_support
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit

    env_file:
      - ../.env.docker

    ports:
      - "8501:8501"

    depends_on:
      - api

volumes:
  postgres_data: