"""
chunk_loader.py

Purpose:
--------
Load chunk artifacts generated by the
ingestion pipeline.

Responsibilities:
-----------------
- Discover chunk artifact files
- Load chunk JSON data
- Return chunk records for embedding

Architecture Philosophy:
------------------------
Simple artifact consumption.
No transformation.
No business logic.
"""

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


class ChunkArtifactLoader:
    def __init__(
        self,
        chunk_root: str,
    ):
        self.chunk_root = Path(chunk_root)

    def load(self) -> list[dict]:

        chunk_records = []

        chunk_files = sorted(self.chunk_root.rglob("*.json"))

        logger.info(f"Found {len(chunk_files)} chunk artifact files.")

        for file_path in chunk_files:
            with open(file_path, "r", encoding="utf-8") as f:
                chunks = json.load(f)

            chunk_records.extend(chunks)

        logger.info(f"Loaded {len(chunk_records)} chunks.")

        return chunk_records


if __name__ == "__main__":
    from app.rag.pipelines.chunk_loader import ChunkArtifactLoader

    loader = ChunkArtifactLoader(chunk_root="artifacts/chunked")

    chunks = loader.load()

    print(len(chunks))
    chunk = chunks[0]
    print(chunk)
    chunk_id = chunk.get("chunk_id")
    text = chunk.get("text")
    document_id = chunk.get("metadata", {}).get("document_id")
